/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BioenergySolutionsRouteImport } from './routes/bioenergy-solutions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjectsPoliciesRouteImport } from './routes/projects-policies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BioenergySolutionsRoute = BioenergySolutionsRouteImport.update({
  id: '/bioenergy-solutions',
  path: '/bioenergy-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPoliciesRoute = ProjectsPoliciesRouteImport.update({
  id: '/projects-policies',
  path: '/projects-policies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bioenergy-solutions': typeof BioenergySolutionsRoute
  '/contact': typeof ContactRoute
  '/projects-policies': typeof ProjectsPoliciesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bioenergy-solutions': typeof BioenergySolutionsRoute
  '/contact': typeof ContactRoute
  '/projects-policies': typeof ProjectsPoliciesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bioenergy-solutions': typeof BioenergySolutionsRoute
  '/contact': typeof ContactRoute
  '/projects-policies': typeof ProjectsPoliciesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/bioenergy-solutions' | '/contact' | '/projects-policies'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/about' | '/bioenergy-solutions' | '/contact' | '/projects-policies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bioenergy-solutions'
    | '/contact'
    | '/projects-policies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BioenergySolutionsRoute: typeof BioenergySolutionsRoute
  ContactRoute: typeof ContactRoute
  ProjectsPoliciesRoute: typeof ProjectsPoliciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bioenergy-solutions': {
      id: '/bioenergy-solutions'
      path: '/bioenergy-solutions'
      fullPath: '/bioenergy-solutions'
      preLoaderRoute: typeof BioenergySolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-policies': {
      id: '/projects-policies'
      path: '/projects-policies'
      fullPath: '/projects-policies'
      preLoaderRoute: typeof ProjectsPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BioenergySolutionsRoute: BioenergySolutionsRoute,
  ContactRoute: ContactRoute,
  ProjectsPoliciesRoute: ProjectsPoliciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
